# Generated by Django 6.1.1 on 2026-09-16 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tryvis Investments Limited', max_length=200)),
                ('tagline', models.CharField(default='Precision engineering. Reliable supply. Built for industry.', max_length=250)),
                ('logo', models.ImageField(blank=True, help_text='Upload the company logo here.', null=True, upload_to='logo/')),
                ('about', models.TextField()),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('values', models.TextField()),
                ('address_line', models.CharField(default='Plot 15, Msigani, Ubungo, Dar es Salaam', max_length=255)),
                ('po_box', models.CharField(blank=True, default='P.O. Box 10952, Dar es Salaam', max_length=100)),
                ('email', models.EmailField(default='tryvisinvestment@gmail.com', max_length=254)),
                ('tin', models.CharField(blank=True, default='156-481-602', max_length=50)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Digits with country code, e.g. 255767644317', max_length=30)),
            ],
            options={
                'verbose_name': 'Company Info',
                'verbose_name_plural': 'Company Info',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('workshop', 'Workshop / Machine Works'), ('fabrication', 'Welding & Fabrication'), ('overhaul', 'Machine Overhauling'), ('gearbox', 'Gearbox Repair'), ('bearings', 'Bearings & Components'), ('other', 'Other')], default='other', max_length=20)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('website', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('label', models.CharField(blank=True, help_text='e.g. Office, Sales, WhatsApp', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='core.companyinfo')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
