# Generated by Django 5.1.15 on 2026-09-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Landscape photo, ideally 1920x1080 or wider.', upload_to='hero/')),
                ('headline', models.CharField(blank=True, help_text='Optional. Overrides the default headline while this slide is showing.', max_length=120)),
                ('subline', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero slide',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. 2022, 7, 4', max_length=30)),
                ('label', models.CharField(help_text='e.g. Serving industry since', max_length=90)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
