# Generated by Django 5.1.15 on 2026-09-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_heroslide_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('logo', models.ImageField(upload_to='brands/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='brela_reg_no',
            field=models.CharField(blank=True, help_text='BRELA Certificate of Incorporation number', max_length=40),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='business_license_no',
            field=models.CharField(blank=True, help_text='Business licence number, e.g. from the municipal council', max_length=60),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='kind',
            field=models.CharField(choices=[('product', 'Product we supply'), ('service', 'Service we offer')], default='service', max_length=10),
        ),
    ]
