# Generated by Django 5.1.15 on 2026-09-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_brand_companyinfo_brela_reg_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(help_text='Where this text appears on the site — shown only in admin.', max_length=150)),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name': 'Site text',
                'verbose_name_plural': 'Site text',
                'ordering': ['key'],
            },
        ),
    ]
